### PR TITLE
C/AL

### PR DESCRIPTION
**Pull request by forki**
I updated to latest FSharp.Formatting but it didn't really work

image

image

/cc @tpetricek @kfuglsang

### CODE REVIEW

**Comment by tpetricek** [comment]
Yeah, this is where the two syntax highlighters start fighting each other.

I think we need to do what @kfuglsang suggested - disable the one in FsReveal on everything that has been highlighted by F# Formatting and probably fix the CSS for C/AL formatting....

**Comment by kfuglsang** [comment]
I just took a look at this. We need a way to figure if FSharp.Formatting did the formatting already.

I'm working on a solution.

**Comment by forki** [comment]
Much better, but still no touchdown. I think the font size is wrong. Ideas?

image

image

image

**Comment by kfuglsang** [comment]
Looks good with https://github.com/fsprojects/FsReveal/pull/78 :)

**Comment by forki** [comment]
mhm. it's still a bit of

**Comment by kfuglsang** [comment]
Looks like this on my machine.

image

image

image

**Comment by forki** [comment]
mhm that looks awesome. but why is it not working on my machine!?

**Comment by kfuglsang** [comment]
Which browser?

I checked in both Chrome and IE 11

**Comment by forki** [comment]
yep. looks broken in both browsers. So I assume there is something else
fucky. Maybe the copy did not work and one of us is seeing a different css
file?

2015-06-14 18:10 GMT+02:00 Kenneth Fuglsang Christensen <
notifications@github.com>:

**Comment by forki** [comment]
it's also misaligned on my other machine

**Comment by forki** [comment]
image

**Comment by forki** [comment]
I found it

**Comment by kfuglsang** [comment]
Cool.

**Comment by forki** [comment]
works

IT WORKS!!! AWESOME! Thank you so much for making this happen.

**Comment by kfuglsang** [comment]
No problem! ;-)

**Comment by forki** [comment]
https://twitter.com/sforkmann/status/610126276498706432

**Comment by tpetricek** [comment]
Looks good - although can we fix the CSS so that the background color is the same in the table cell with the code and the table cell with the line numbers? (I think it used to be the same before...)

**Pull request merged**
