### PR TITLE
Transparent background on code snippets

### PR DESCRIPTION
**Pull request by kfuglsang**
This PR is better.

It solves @tpetricek's request in  #76

### CODE REVIEW

**Comment by tpetricek** [comment]
Neat :-). I think I also figured out how to get rid of the black-ish borders that FsReveal creates, so adding that to the default template would be nice too. I think it was this line: https://github.com/tpetricek/Talks/blob/master/2015/literate-programming/london/slides/custom.css#L20

(But I can send my own PR :-))

**Comment by forki** [comment]
@tpetricek yes please send pr. I'll merge and release asap

**Comment by forki** [comment]
image

**Comment by forki** [comment]
image

and borders are gone.

**Comment by tpetricek** [comment]
Nice, thanks!

**Pull request merged**
